import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UIProvider } from "@/app/context/UIProvider";
import { NavControl, Theme } from "@/app/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Matt Petts | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <UIProvider>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <Theme>
                        <div className="flex items-start justify-start">
                            <div className="flex-1 relative">
                                <NavControl />
                                {children}
                            </div>
                        </div>
                    </Theme>
                </body>
            </UIProvider>
        </html>
    );
}
